[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
    "probe-rs",
    "run",
    "--chip",
    "STM32U575ZITxQ",
    "--log-format",
    "{[ {t:010} {L:bold}{F:white}:{l:white}]} {s}",
]
rustflags = [
    # LLD (shipped with the Rust toolchain) is used as the default linker
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=-Tdefmt.x",
    "-Clink-arg=-nmagic",
    # "-C", "link-arg=-Tstlog.x",

    # if you run into problems with LLD switch to the GNU linker by commenting out
    # this line
    # "-C", "linker=arm-none-eabi-ld",

    # if you need to link to pre-compiled C libraries provided by a C toolchain
    # use GCC as the linker by commenting out both lines above and then
    # uncommenting the three lines below
    # "-C", "linker=arm-none-eabi-gcc",
    # "-C", "link-arg=-Wl,-Tlink.x",
    # "-C", "link-arg=-nostartfiles",
    "-Z", "threads=8"
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info"

[profile.dev]
debug = true

[profile.release]
debug = true
